id = "nexus"
name = "Nexus"
description = "Language support for the Nexus (.nx) programming language"
version = "0.1.0"
schema_version = 1
authors = ["Xyndra"]
repository = "https://github.com/Xyndra/nexus"

[language_servers.nexus-lsp]
name = "Nexus LSP"
languages = ["Nexus"]

[grammars.nexus]
repository = "https://github.com/Xyndra/tree-sitter-nexus"
rev = "03c5b92acc696ce4c31142af57c006edaf49b117"
