[package]
name = "nexus-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
nexus-core.workspace = true
nexus-lexer.workspace = true
nexus-parser.workspace = true
nexus-types.workspace = true

[lib]
name = "nexus_lsp"
path = "src/lib.rs"
